server:
  address: 10.34.2.28
  port: 8899


spring:
  datasource:
    name: test
    url: jdbc:mysql://myaws:3306/crm
    username: root
    password: newPwd
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:com/thruman/dao/*.xml
  type-aliases-package: com.thruman.dao


#通用mapper配置
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
    - tk.mybatis.mapper.common.Mapper2
  notEmpty: true


#boot-actuator
#启用shutdown
#management:
#  security:
#    enabled: false
#  port: 9999
#  address: 127.0.0.1
#  context-path: /admin
#endpoints:
#  shutdown:
#    enabled: true
#    sensitive: false
#    path: /close



#日志配置
logging:
  config: classpath:logback.xml